[package]
name = "faer_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
faer = "0.19.4"
nalgebra-sparse = { version="0.10.0", features=["io"] }
suitesparse_sys = "0.1.3"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "solve"
harness = false